console:
  welcome:
    msg: REMOTE UPDATE AGAIN and AGAIN 3 -- A dave demo service has started.  This message originates from the global (all services, all environments) properties file, namely "/app-config/application.yaml".
